// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';

export function ApplicationMenu():Promise<menu.Menu>;

export function LpsAndTimeToFile(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function ModuleEnv():Promise<void>;

export function ModuleSend(arg1:string):Promise<void>;

export function ModuleStart(arg1:string,arg2:string):Promise<void>;

export function ModuleStyleSerialSend(arg1:Array<number>):Promise<void>;

export function OpenAndTimeToFile(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function ParseData(arg1:Array<number>):Promise<void>;

export function PortList():Promise<Array<string>>;

export function QuatAndTimeToFile(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function ReceiveData(arg1:any):Promise<void>;

export function SelectedPort(arg1:string):Promise<void>;

export function SerialByteSend(arg1:Array<number>):Promise<void>;

export function SerialStart():Promise<void>;

export function SerialStop():Promise<void>;

export function SerialTextSend(arg1:string):Promise<void>;

export function VoltageToFile(arg1:Array<number>):Promise<void>;
