// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu() {
  return window['go']['handler']['App']['ApplicationMenu']();
}

export function LpsAndTimeToFile(arg1, arg2) {
  return window['go']['handler']['App']['LpsAndTimeToFile'](arg1, arg2);
}

export function ModuleEnv() {
  return window['go']['handler']['App']['ModuleEnv']();
}

export function ModuleSend(arg1) {
  return window['go']['handler']['App']['ModuleSend'](arg1);
}

export function ModuleStart(arg1, arg2) {
  return window['go']['handler']['App']['ModuleStart'](arg1, arg2);
}

export function ModuleStyleSerialSend(arg1) {
  return window['go']['handler']['App']['ModuleStyleSerialSend'](arg1);
}

export function OpenAndTimeToFile(arg1, arg2) {
  return window['go']['handler']['App']['OpenAndTimeToFile'](arg1, arg2);
}

export function ParseData(arg1) {
  return window['go']['handler']['App']['ParseData'](arg1);
}

export function PortList() {
  return window['go']['handler']['App']['PortList']();
}

export function QuatAndTimeToFile(arg1, arg2) {
  return window['go']['handler']['App']['QuatAndTimeToFile'](arg1, arg2);
}

export function ReceiveData(arg1) {
  return window['go']['handler']['App']['ReceiveData'](arg1);
}

export function SelectedPort(arg1) {
  return window['go']['handler']['App']['SelectedPort'](arg1);
}

export function SerialByteSend(arg1) {
  return window['go']['handler']['App']['SerialByteSend'](arg1);
}

export function SerialStart() {
  return window['go']['handler']['App']['SerialStart']();
}

export function SerialStop() {
  return window['go']['handler']['App']['SerialStop']();
}

export function SerialTextSend(arg1) {
  return window['go']['handler']['App']['SerialTextSend'](arg1);
}

export function VoltageToFile(arg1) {
  return window['go']['handler']['App']['VoltageToFile'](arg1);
}
