// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationMenu() {
  return window['go']['handler']['App']['ApplicationMenu']();
}

export function SerialSend(arg1) {
  return window['go']['handler']['App']['SerialSend'](arg1);
}

export function SerialStart() {
  return window['go']['handler']['App']['SerialStart']();
}

export function SerialStop() {
  return window['go']['handler']['App']['SerialStop']();
}
