// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendError(arg1) {
  return window['go']['model']['Hub']['SendError'](arg1);
}

export function SendText(arg1) {
  return window['go']['model']['Hub']['SendText'](arg1);
}
