// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SerialMonitor() {
  return window['go']['main']['App']['SerialMonitor']();
}

export function SerialStop() {
  return window['go']['main']['App']['SerialStop']();
}
